[run]
branch = True
source = codecov

[report]
exclude_lines =
    pragma: no cover
    def __repr__
    if .debug:
    raise NotImplementedError
    if __name__ == .__main__.:
    
ignore_errors = True

[html]
directory = coverage_html_report

omit =
    venv/*
    tests/*
    setup.py
